name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
      - uses: changesets/action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          version: npm run ci:version
          publish: npm run ci:publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
